'%prod':
    keycloak:
        url: http://localhost:8180
    quarkus:
        oidc:
            auth-server-url: ${keycloak.url}/realms/quarkus
quarkus:
    http:
        auth:
            permission:
                authenticated:
                    paths: /*
                    policy: authenticated
        test-port: 8080
            
    keycloak:
        devservices:
            realm-path: default-tenant-realm.json,tenant-a-realm.json
            port: 8081
            show-logs: true
        admin-client: 
            grant-type: CLIENT_CREDENTIALS
            username: alice
            password: alice
            realm: tenant-a
            client-id: multi-tenant-client
            client-secret: secret
    log:
        category:
            "org.htmlunit":
                level: ERROR
    oidc:
        devui:
            grant:
                type: code
        application-type: service
        client-id: multi-tenant-client
        
